# Generated by Django 4.2.11 on 2024-08-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master_tbl_doctor',
        ),
    ]
