# Generated by Django 4.2.11 on 2024-10-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleapp', '0003_master_tbl_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trn_tbl_posted_review',
        ),
    ]
