# Generated by Django 4.2.11 on 2024-10-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleapp', '0005_trn_tbl_posted_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trn_tbl_posted_review',
        ),
    ]
