# Generated by Django 4.2.11 on 2024-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleapp', '0006_delete_trn_tbl_posted_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trn_tbl_posted_review',
            fields=[
                ('fld_slno', models.AutoField(primary_key=True, serialize=False)),
                ('fld_rn', models.IntegerField(db_index=True, null=True)),
                ('fld_rf_id', models.IntegerField(db_index=True, null=True)),
                ('fld_review_sw_id', models.CharField(max_length=255, null=True)),
                ('fld_review_id', models.CharField(max_length=255, null=True)),
                ('fld_author_name', models.TextField(null=True)),
                ('fld_review_date', models.CharField(max_length=255, null=True)),
                ('fld_place_id', models.TextField(null=True)),
                ('fld_place_name', models.TextField(null=True)),
                ('fld_rating', models.TextField(null=True)),
                ('fld_review_text', models.TextField(null=True)),
                ('fld_review_link', models.TextField(null=True)),
                ('fld_doc_sw_id', models.TextField(null=True)),
                ('fld_doc_id', models.TextField(null=True)),
                ('fld_doc_name', models.TextField(null=True)),
                ('fld_posted_as_id', models.TextField(null=True)),
                ('fld_posted_as_name', models.TextField(null=True)),
                ('fld_loggedin_user_id', models.TextField(null=True)),
                ('fld_is_active', models.CharField(db_index=True, max_length=2, null=True)),
                ('fld_system_inserted_datetime', models.CharField(default=0, max_length=50)),
                ('fld_modified_no', models.IntegerField(null=True)),
                ('fld_modified_datetime', models.CharField(max_length=50, null=True)),
                ('fld_is_deleted', models.CharField(db_index=True, max_length=2, null=True)),
                ('fld_is_deleted_datetime', models.CharField(max_length=100, null=True)),
                ('fld_reason_for_deletion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'trn_tbl_posted_review',
            },
        ),
    ]
